#!/bin/bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^#[0-9]+ - .*"
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "A mensagem de commit deve ser no formato: '<numero da issue> - <commit message>'. Por exemplo, '1234 - feature: add botão'"
  exit 1
fi
