#!/bin/bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^#[0-9]+ - .*"
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "A mensagem de commit deve ser no formato: '#<numero da issue> - <commit message>'. Por exemplo, '#1234 - feature: add botão'"
  exit 1
fi


NUM_ISSUE= $(echo $START_LINE | cut -d ' ' -f1 | cut -c 2-)
URL="https://api.github.com/repos/renanamr/Banco_DIM0517/issues/$NUM_ISSUE"

response=$(curl -s -o /dev/null -I -w "%{http_code}" $URL)
if [ "$response" =~ "200" ]; then
    echo "Utilize um número de issue válido"
    exit 1  # Impede o commit de ser realizado
fi